title: Bash Benchmarks
email: peter@forret.com
description: >- # this means to ignore newlines until "baseurl:"
  List of bash benchmarks, as mentioned on <a href='https://blog.forret.com/tag/bash-benchmark/'>blog.forret.com</a>
baseurl: "/bash_benchmarks" # the subpath of your site, e.g. /blog
url: "https://pforret.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pforret
github_username:  pforret

# Build settings
theme: jekyll-theme-cayman
google_analytics: G-TR8NTB5WL0
plugins:
  - jekyll-feed
  - jekyll-toc
